name: CMake

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch: ~

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}/bwapi
      run: cmake -B ${{github.workspace}}/bwapi/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/bwapi/build --config Release
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}/bwapi
      run: cmake -B ${{github.workspace}}/bwapi/build -DCMAKE_BUILD_TYPE=Debug

    - name: Test
      working-directory: ${{github.workspace}}/bwapi/build
      run: cmake --build ${{github.workspace}}/bwapi/build --config Debug --target BWAPILIB_coverage

  package:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}/bwapi
      run: cmake -B ${{github.workspace}}/bwapi/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/bwapi/build --config Release
