name: CMake

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch: ~

jobs:
  build-macos:
    runs-on: macos-latest
    
    strategy:
      matrix:
        compiler: [gcc, clang]
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}/bwapi
      run: cmake -B ${{github.workspace}}/bwapi/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${{matrix.compiler}}

    - name: Build
      run: cmake --build ${{github.workspace}}/bwapi/build --config Release
  
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install LCov
      shell: bash
      run: sudo apt-get install lcov > /dev/null

    - name: Configure CMake
      working-directory: ${{github.workspace}}/bwapi
      run: cmake -B ${{github.workspace}}/bwapi/build -DCMAKE_BUILD_TYPE=Debug

    - name: Run Tests
      working-directory: ${{github.workspace}}/bwapi/build
      run: cmake --build ${{github.workspace}}/bwapi/build --config Debug --target BWAPILIB_coverage

    - name: Report code coverage
      uses: actions/upload-artifact@v2
      with:
        name: BWAPILIB_coverage
        path: ${{github.workspace}}/bwapi/build/BWAPILIB_coverage

  package-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      working-directory: ${{github.workspace}}/bwapi
      run: cmake -B ${{github.workspace}}/bwapi/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x86

    - name: Build
      run: cmake --build ${{github.workspace}}/bwapi/build --config Release
